WEEK-4 리팩토링과 테스트코드 구현
kakao-clean-fe/github-issues pull request #87
Opened 2022-11-30 14:28 UTC by Sotaneum

# TODO
- 이전 누락 작업 반영
  - [ ] (선택적용) [prefetch](https://web.dev/link-prefetch/) 설정
  - [ ] new label 영역 정보 localStorage에 저장
- 이전 PR 반영
  - [ ] 연관된 상태는 묶어서 관리 https://github.com/kakao-clean-fe/github-issues/pull/54#discussion_r1028856946
  - [ ] 오류가 발생할때 잘 처리 되는지 까지도 테스트 https://github.com/kakao-clean-fe/github-issues/pull/54#discussion_r1028891602
- [x] vitest 설치
- [ ] 단위 테스트코드 추가
- 기타 개선 사항
  - [ ] 이벤트 위임 방식 적용하기
  - [ ] label 수정
  - [ ] label 삭제

2022-12-01 08:58 UTC, crongro requested changes
리뷰남겨드린 것 꼭 수정해보세요~

2022-12-01 08:58 UTC, crongro commented on src/core/LabelCreator.js
> +    this._data.subscribe((store) => {
_data 보다는 구체적인 이름이면 더 좋죠.

2022-12-01 08:58 UTC, crongro commented on src/core/LabelCreator.js
> +      const find = this._getElement();
자주쓰는 유틸은 더 짧게도 가능하죠. $ 라던가.

2022-12-01 08:58 UTC, crongro commented on src/core/LabelCreator.js
> +      }
이렇게 짧다면 3항연산자?

2022-12-01 08:58 UTC, crongro commented on src/core/LabelCreator.js
> +      if (!this._data.value.prev) {
이렇게 긍정 조건을 먼저 체크하시고 해보시면 들여쓰기가 줄 것 같아요.
if (this._data.value.prev) { }

2022-12-01 08:58 UTC, crongro commented on src/core/LabelCreator.js
> +          throw e;
지금 코드가 좀 길기 때문에 catch 뒤에 있는 코드도 메서드로 분리하는 것도 좋을것 같아요.
status 는 400, 500 안에도 여러개임으로 그것까지 고려하면 좋죠.

2022-12-01 08:58 UTC, crongro commented on src/core/LabelList.js
> +  window.addEventListener("click", async (e) => {
콜백함수를 별도도 분리선언하는 습관을 가지시면 더 좋겠습니다.

2022-12-01 11:39 UTC, Sotaneum commented on src/core/LabelCreator.js
> +    this._data.subscribe((store) => {
_data 대신 _label로 변경해 보았습니다. ([32a59a3](https://github.com/kakao-clean-fe/github-issues/pull/87/commits/32a59a31939a90bb74871666baa7ca4871dfe3a4))

2022-12-01 11:40 UTC, Sotaneum commented on src/core/LabelCreator.js
> +      const find = this._getElement();
`find`를 `$`로 변경해보았습니다. ([c4c0991](https://github.com/kakao-clean-fe/github-issues/pull/87/commits/c4c0991fc1d4a8c2850e8d110c5dd9f15b6a9b2e))

2022-12-01 11:43 UTC, Sotaneum commented on src/core/LabelCreator.js
> +      if (!this._data.value.prev) {
긍정 조건을 먼저 체크하도록 수정했습니다 ([974df8b](https://github.com/kakao-clean-fe/github-issues/pull/87/commits/974df8b7aebba504e5c73290d1ae46b61b18bbe8))

2022-12-01 12:03 UTC, Sotaneum commented on src/core/LabelCreator.js
> +          throw e;
메서드 분리 진행했습니다 ([efacd95](https://github.com/kakao-clean-fe/github-issues/pull/87/commits/efacd956545c77f75ac1e7c1d3cf9b43633239fc))

2022-12-03 10:03 UTC, crongro approved these changes
리팩토링까지 수고하셨어요 잘하셨습니다.
함수는 생각하시는 것보다 더 작게 유지하시면 아주 더 좋은코드가 될 겁니다.

2022-12-03 10:03 UTC, crongro commented on src/core/LabelCreator.js
> +      this.saveData({ description: e.target.value })
destructuring 문법도 꼭 익혀서 활용해보세요.

2022-12-03 10:03 UTC, crongro commented on src/core/LabelList.js
> +    );
이 함수가 어떤것인지 잘 모르겠지만, 파라미터  3개보다 한개를 받도록 변경하는 건 어떨까 싶네요.
this._labelCreateUI(editBtn);

2022-12-03 10:03 UTC, merged